name: "Vercel Deploy"
description: "github action for vercel deploy"
author: "Zero <GitHub: whatwewant>"
branding:
  icon: "cloud-lightning"
  color: "green"
inputs:
  token:
    required: true
    description: "vercel token. You can get it from https://vercel.com/account/tokens"
  org-id:
    required: false
    description: "vercel organization id. See project settings page -> General -> Team ID"
  project-id:
    required: false
    description: "vercel project id. See project settings page -> General -> Project ID"

outputs:
  preview-url:
    description: "preview url"
    value: ${{ steps.deploy.outputs.preview-url }}

runs:
  using: composite
  steps:
    - name: Set up Zmicro
      uses: zmicro-design/action-setup-zmicro@v1

    # - name: Set up Pipeline
    #   shell: bash
    #   run: zmicro package install pipeline

    - name: Vercel Prepare
      shell: bash
      run: |
        which npm > /dev/null 2>&1
        if [ $? -ne 0 ]; then
          echo "npm not found, please check your node installation"
          exit 1
        fi

        npm i -g vercel

    - name: Vercel Deploy
      shell: bash
      id: deploy
      run: |
        export VERCEL_TOKEN=${{ inputs.token }}
        export VERCEL_ORG_ID=${{ inputs.org-id }}
        export VERCEL_PROJECT_ID=${{ inputs.project-id }}

        LOG_INFO() {
          echo -e "\033[32m[$(date)] $1\033[0m"
        }

        LOG_ERROR() {
          echo -e "\033[31m[$(date)] $1\033[0m"
        }

        LOG_INFO "Pulling Vercel environment ..."
        vercel pull --yes --environment=preview --token=$VERCEL_TOKEN 2>&1
        if [ $? -ne 0 ]; then
          LOG_ERROR "Failed to pull Vercel environment."
          exit 1
        fi

        LOG_INFO "Building Vercel project ..."
        vercel build 2>&1
        if [ $? -ne 0 ]; then
          LOG_ERROR "Failed to build Vercel project."
          exit 1
        fi

        LOG_INFO "Deploying Vercel project ..."
        url=$(vercel deploy --token $VERCEL_TOKEN --prebuilt)
        exit_code=$?
        if [ $exit_code -ne 0 ]; then
          LOG_ERROR "Failed to deploy Vercel project."
          exit 1
        fi

        echo "preview-url=$url" >> $GITHUB_OUTPUT

    - name: Commit PR
      uses: actions/github-script@v7
      with:
        script: |
          // Check if this is a pull request context
          const isPR = context.eventName === 'pull_request' || 
                      context.payload.pull_request !== undefined ||
                      context.issue?.pull_request !== undefined
          if (!isPR) {
            console.log('Not a pull request context, skipping comment.')
            return
          }

          // Get PR number
          const prNumber = context.issue.number || 
                          context.payload.pull_request?.number ||
                          context.payload.number
          if (!prNumber) {
            console.log('Could not determine PR number, skipping comment.')
            return
          }

          // create comment
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Preview deployed to: ${{ steps.deploy.outputs.preview-url }}`
          })
