name: "Vercel Deploy"
description: "github action for vercel deploy"
author: "Zero <GitHub: whatwewant>"
branding:
  icon: "cloud-lightning"
  color: "green"
inputs:
  token:
    required: true
    description: "vercel token. You can get it from https://vercel.com/account/tokens"
  org-id:
    required: false
    description: "vercel organization id. See project settings page -> General -> Team ID"
  project-id:
    required: false
    description: "vercel project id. See project settings page -> General -> Project ID"

outputs:
  preview-url:
    description: "preview url"

runs:
  using: composite
  steps:
    - name: Set up Zmicro
      uses: zmicro-design/action-setup-zmicro@v1

    # - name: Set up Pipeline
    #   shell: bash
    #   run: zmicro package install pipeline

    - name: Vercel Prepare
      shell: bash
      run: |
        which npm > /dev/null 2>&1
        if [ $? -ne 0 ]; then
          echo "npm not found, please check your node installation"
          exit 1
        fi

        npm i -g vercel

    - name: Vercel Deploy
      shell: bash
      run: |
        export VERCEL_TOKEN=${{ inputs.token }}
        export VERCEL_ORG_ID=${{ inputs.org-id }}
        export VERCEL_PROJECT_ID=${{ inputs.project-id }}

        vercel pull --yes --environment=preview --token=$VERCEL_TOKEN 2>&1
        if [ $? -ne 0 ]; then
          echo "[$(date)] Failed to pull Vercel environment"
          exit 1
        fi

        vercel build 2>&1
        if [ $? -ne 0 ]; then
          echo "[$(date)] Failed to build Vercel project"
          exit 1
        fi

        url=$(vercel deploy --token $VERCEL_TOKEN --prebuilt)
        exit_code=$?
        if [ $exit_code -ne 0 ]; then
          echo "[$(date)] Failed to deploy Vercel project"
          exit 1
        fi

        echo "preview-url=$url" >> $GITHUB_OUTPUT