name: pipeline

stages:
  - name: test
    jobs:
      - name: test
        steps:
          - name: show env
            command: env
          - name: test
            command: |
              echo "[$(date)] test ok"
